### ISSUE TITLE
Failed to load DLL: foo_mg.dll  in Windows 10

### ISSUE THREAD

**Issue by e19940604** [oxyflour/foo_mg#4]
foo_mg work perfectly win7 , 
but last day i update my system to win10  it shows 

Failed to load DLL: foo_mg.dll
Reason: This component is missing a required dependency, or was made for different version of foobar2000.

Is there any dependency  need to install ?

**Comment by oxyflour** [comment]
Hello! Are you still using the v0.22 binary? I've just released a new [0.22.1 binary](https://github.com/oxyflour/foo_mg/releases/download/0.22.1/foo_mg_v0.22.1.zip), which has been tested with latest foobar2000 v1.3.14 on Windows 10 15031. Please have a try with that.

Thank you for your feedback! Really glad that my project is helpful for somebody :-)

**Comment by e19940604** [comment]
Cool , I used your plugin about a year  , haha. 

But it still not work for foobar2000 v1.3.14 new 0.22.1 binary in both standard install and portable 
![default](https://cloud.githubusercontent.com/assets/2912526/23153129/b88c42e2-f841-11e6-9b93-fa4465a6dacc.PNG)

OS system is Windows 10 Version 1607 x64 
Just reinstall two days ago , so I think maybe there are some driver or program should be install 

![default](https://cloud.githubusercontent.com/assets/2912526/23153202/1567aac4-f842-11e6-93d0-542ca15a9861.PNG)

**Comment by oxyflour** [comment]
Can you try installing the Visual C++ 2010 redistributable? The binary was compiled with Visual Studio 2010.

https://www.microsoft.com/en-US/Download/confirmation.aspx?id=14632

**Comment by e19940604** [comment]
Finally , after install 32-bit runtime , it works !!
Thanks for updating binary and solving my question :D !!

**Comment by oxyflour** [comment]
Cheers!

I've updated the readme file for the runtime dependency. Closing this :-)
